Api testing
Paw3lUlita/carinaHomeWork pull request #1
Opened 2023-03-08 07:39 UTC by Paw3lUlita

2023-03-09 10:52 UTC, vboltrukanis requested changes

2023-03-09 10:52 UTC, vboltrukanis commented on src/main/java/org/example/carina/demo/api/RetrieveCollectionGetMethod.java
> +public class RetrieveCollectionGetMethod extends AbstractApiMethodV2 {
You don't need to use Get and Retrieve in the same place, it is kinda repeating.
`RetrieveCollectionMethod`
`GetCollectionMethod`

2023-03-09 10:52 UTC, vboltrukanis commented on src/main/java/org/example/carina/demo/api/RetrieveCollectionGetMethod.java
> +public class RetrieveCollectionGetMethod extends AbstractApiMethodV2 {
The same can be used to other names as well.

2023-03-09 10:52 UTC, vboltrukanis commented on src/main/java/org/example/carina/demo/api/RetrievePhotosForCollectionGetMethod.java
> +    public RetrievePhotosForCollectionGetMethod(String param) {
You better give more descriptive name to parameters: `collectionId`

2023-03-09 10:52 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/RetrieveCollectionGetMethodTest.java
> +        retrieveCollectionGetMethod.validateResponseAgainstSchema("api/retrieveCollection/_get/errorRs.schema");
not necessary, but i usually see smth like rs_error.schema

2023-03-09 10:52 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/RetrieveCollectionGetMethodTest.java
> +    private static final String API_KEY = "NmrYpUAIdhsOs8C3KCRK7emmcNzud_ZwkrUK9QAU-KI";
this is secret, do not expose it in public repo. 
What you can do is to create a variable in config.properties and get this variable here via: `Configuration.getEnvArg("api_key")`

2023-03-09 10:52 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/RetrieveCollectionGetMethodTest.java
> +    private static final String API_KEY = "NmrYpUAIdhsOs8C3KCRK7emmcNzud_ZwkrUK9QAU-KI";
Also this can be moved to Method class lvl, not test level.

2023-03-09 10:52 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/SearchForCollectionGetMethodTest.java
> +        searchForCollectionGetMethod.addUrlParameter("query", "cat");
you can pass this `cat` as a parameter into `SearchForCollectionGetMethod` that would make more sense

2023-03-09 10:52 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/SearchForCollectionGetMethodTest.java
> +    public void whenQueryParameterIsPassedEndpointShouldReturnProperResponseAndStatus() {
test names should be descriptive, but much shorter)
`getCollectionsSuccessTest`
`getCollectionMissingQueryParamTest`
`getCollectionMissingAccessTokenTest`

2023-03-10 09:16 UTC, Paw3lUlita commented on src/test/java/org/example/carina/demo/api/SearchForCollectionGetMethodTest.java
> +        searchForCollectionGetMethod.addUrlParameter("query", "cat");
I' ve tried, but it seems to be more convenient for missing query test, when user would forgot to pass this parameter. I've tried to pass null to the constructor, but test without query didn't pass

2023-03-15 10:55 UTC, vboltrukanis requested changes

2023-03-15 10:55 UTC, vboltrukanis commented on .gitignore
> +.idea/
You added this folder into gitignore, but there is still some files available in github, remove them.

2023-03-15 10:55 UTC, vboltrukanis commented on src/main/java/org/example/carina/demo/api/RetrieveCollectionMethod.java
> +        replaceUrlPlaceholder("api_key", Configuration.getEnvArg("api_key"));
use `addUrlParameter("client_id", "...");` instead.

2023-03-15 10:55 UTC, vboltrukanis commented on src/main/resources/_config.properties
> +DEMO.api_key=NmrYpUAIdhsOs8C3KCRK7emmcNzud_ZwkrUK9QAU-KI
do not expose sensitive data in github. You can leave it empty here and place a reminder in README to place here a key.

2023-03-15 10:55 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/RetrieveCollectionMethodTest.java
> +}
Empty line in the end of file. It is displayed here and will be autoformatted by intelij if you tru to autoformat.

2023-03-15 12:10 UTC, vboltrukanis requested changes

2023-03-15 12:10 UTC, vboltrukanis commented on src/main/java/org/example/carina/demo/api/SearchForCollectionMethod.java
> +@Endpoint(url = "${base_url}/search/collections/?client_id=${api_key}", methodType = HttpMethodType.GET)
`client_id` suggestion update in all files

2023-03-15 12:10 UTC, vboltrukanis commented on src/main/resources/_config.properties
> +DEMO.api_key=
I want to see a README that will help me to find this variable and insert required key.

2023-03-15 12:10 UTC, vboltrukanis commented on src/test/java/org/example/carina/demo/api/RetrieveCollectionMethodTest.java
> +    @MethodOwner(owner = "pawelUlita")
```suggestion
    @MethodOwner(owner = "pulita")
```
This is not necessary, but it is a company standard

2023-03-16 14:59 UTC, vboltrukanis approved these changes

2023-03-16 14:59 UTC, vboltrukanis commented on src/main/resources/_config.properties
> +DEMO.api_key=
Why you don't like documentation so much)

2023-03-17 07:38 UTC, merged